### ISSUE TITLE
how to add this theme to vim?

### ISSUE THREAD

**Issue by jacobsayono** [comfysage/dawn.vim#1]
hey can you let me know step by step how to add this theme to vim?

**Comment by comfysage** [comment]
An _Installation & Usage_ section has been added to the [README](https://github.com/CrispyBaccoon/dawn.vim/blob/mega/README.md) in this commit: [28bbe2d](https://github.com/CrispyBaccoon/dawn.vim/commit/28bbe2d1c2534e8f9575731cbb7b3a3eb11fb65c) 

> If you use [vim-plug](https://github.com/junegunn/vim-plug) you can add this to your    `.vimrc` / `init.vim`:
>   
>   ```Vim
>   Plug 'crispybaccoon/dawn.vim'
>   ```
>   
>   Then:
>   
>   ```Vim
>   set background=dark " Set to light for a light variant
>   colorscheme dawn
>   ```

**Comment by jacobsayono** [comment]
hi, can you check my `.vimrc`?
i'm not sure what additional lines i added that may have overwritten your theme. the colors i see are different from your theme example! and i have saved and restarted my terminal.

in vim, i also did:
`source .vimrc` to save
`:PlugInstall` to load your theme plugin

thank you so much for the help!

```vim
call plug#begin('~/.vim/plugged')
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-default branch
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

" Initialize plugin system
" - Automatically executes `filetype plugin indent on` and `syntax enable`.
call plug#end()
" You can revert the settings after the call like so:
"   filetype indent off   " Disable file-type-specific indentation
"   syntax off            " Disable syntax highlighting




" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Load an indent file for the detected file type.
filetype indent on

Plug 'crispybaccoon/dawn.vim'

set background=dark
colorscheme dawn

" Turn syntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set number

" Highlight cursor line underneath the cursor horizontally.
"set cursorline

" Highlight cursor line underneath the cursor vertically.
"set cursorcolumn

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4

" Use space characters instead of tabs.
set expandtab

" Do not save backup files.
set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=10

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

" Set the commands to save in history default number is 20.
set history=1000

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
```

**Comment by comfysage** [comment]
This codeblock is often added to your nvim/vim config to fix problems with themes not showing up properly.

```vim
" Access full color space
if (has("termguicolors"))
  set termguicolors
endif

" sometimes fixes problems on some terminals
set t_Co=256
```

**Comment by jacobsayono** [comment]
hey! thanks for this. i added the code block to .vimrc -- it improved and have similar colors as your theme. however, some objects are not being colored. here are some examples of python and c++ code, compared side by side to your screenshots (yours is on the left):

C++:
![Screenshot from 2022-08-30 01-07-40](https://user-images.githubusercontent.com/46827431/187385966-71220a0f-854e-435c-b253-81a5b6ff3780.png)

Python:
![Screenshot from 2022-08-30 01-12-17](https://user-images.githubusercontent.com/46827431/187385977-68c3278b-4a04-4bf0-8457-3fc5c6eeb454.png)

it seems the yellow and red colors aren't showing
is this expected? thanks again ~

**Comment by comfysage** [comment]
More objects are highlighted in my screenshots with the help of treesitter. [treesitter](https://github.com/nvim-treesitter/nvim-treesitter) is a popular plug-in that I highly advise you to use. In short, it understands your code and tries to convey more information about the code (it understands codeblock, functions, etc. .)

**Comment by jacobsayono** [comment]
thanks for this.

i tried installing nvim-treesitter by adding this line to .vimrc:
`Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}`

but when i try to install the language parser:
`:TSInstall python`
vim returns:
`E492: Not an editor command: TSInstall`

sorry in advance as i'm new to customizing vim! thanks for the help if you've done this before.

i've installed neovim and other dependencies, `sudo make install` was successful after some errors that i fixed but i come across this last error when trying to `make`:
```
jacobsayono@JS:~/git/neovim$ sudo make install
cd .deps && \
	cmake -G 'Ninja'   \
	 /home/jacobsayono/git/neovim//third-party
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
make: *** [Makefile:114: build/.ran-third-party-cmake] Error 1
```
i have also tried installing `ninja-build`

does tree-sitter only work for nvim and not vim?

here's where i'm stuck right now:
![Screenshot from 2022-08-30 16-34-02](https://user-images.githubusercontent.com/46827431/187561928-826e1391-c3fa-4f92-b728-932bf9cfb4bb.png)

also... curious why i have a bunch of lines/underscores on a blank vim lol. is this normal?

**Comment by jacobsayono** [comment]
update:
horizontal lines removed when i remove these lines in my .vimrc:

`colorscheme dawn`

but removes your theme. seems like your theme may have a bug (or incorrect color) for blank pages?

**Comment by comfysage** [comment]
Treesitter's full name is `nvim-treesitter`. When a plugin name contains nvim it only works for neovim. Regardless of treesitter I advise you to use neovim instead of vim, as many new plugins and features (like lsp) are only available for neovim.

If you want to install neovim than I advise you to either [build from source](https://github.com/neovim/neovim/wiki/Building-Neovim) or [install with an appimage](https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package).

** As for the bug with the random lines on EndOfBuffer **
Thanks for the headsup about this. After testing this myself it turns out that vim has more problems with linking certain Groups than neovim.

This issue is added to the bottom of the readme since [c7e7c59](https://github.com/CrispyBaccoon/dawn.vim/commit/c7e7c5934939ca0fbc8401a9f8a973c1e31152a2).
